name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: cd for_transducer_interpreter && cargo build --all-targets --verbose
      - name: Test
        run: cd for_trandsucer_interpreter && cargo test

